-- ============================================================
-- TEMPLATE DEFINITIVO DE BANCO DE DADOS SUPABASE (TECX PDV)
-- Este script cria toda a estrutura de tabelas, índices, RLS, 
-- triggers e funções necessárias para rodar um novo cliente PDV.
-- Cada tabela ativa e cria suas próprias regras de RLS imediatamente.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------
-- 1. STORES (Lojas / Clientes)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.stores (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    owner_id UUID,
    owner_email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    logo_url TEXT,
    theme_colors JSONB DEFAULT '{"primary": "#800080", "secondary": "#4B0082", "background": "#121212", "surface": "#1E1E1E"}'::jsonb,
    is_active BOOLEAN DEFAULT true,
    plan_value NUMERIC DEFAULT 0,
    subscription_end_date TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para stores" ON public.stores;
DROP POLICY IF EXISTS "Permite modificacao para stores" ON public.stores;
CREATE POLICY "Permite leitura publica para stores" ON public.stores FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para stores" ON public.stores FOR ALL USING (true);

-- ------------------------------------------------------------
-- 2. CATEGORIES (Categorias do Cardápio)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para categories" ON public.categories;
DROP POLICY IF EXISTS "Permite modificacao para categories" ON public.categories;
CREATE POLICY "Permite leitura publica para categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para categories" ON public.categories FOR ALL USING (true);

-- ------------------------------------------------------------
-- 3. MENU ITEMS (Itens / Produtos do Cardápio)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    image TEXT,
    is_available BOOLEAN DEFAULT true,
    is_combo BOOLEAN DEFAULT false,
    eligible_for_combo BOOLEAN DEFAULT false,
    allowed_addons JSONB DEFAULT '[]'::jsonb,
    selected_addons JSONB DEFAULT '[]'::jsonb,
    "addonCategoryIds" JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para menu_items" ON public.menu_items;
DROP POLICY IF EXISTS "Permite modificacao para menu_items" ON public.menu_items;
CREATE POLICY "Permite leitura publica para menu_items" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para menu_items" ON public.menu_items FOR ALL USING (true);

-- ------------------------------------------------------------
-- 4. ADDONS (Adicionais e Complementos)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.addons (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para addons" ON public.addons;
DROP POLICY IF EXISTS "Permite modificacao para addons" ON public.addons;
CREATE POLICY "Permite leitura publica para addons" ON public.addons FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para addons" ON public.addons FOR ALL USING (true);

-- ------------------------------------------------------------
-- 5. SETTINGS (Configurações da Loja)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE UNIQUE,
    opening_time TEXT DEFAULT '18:00:00',
    closing_time TEXT DEFAULT '23:30:00',
    manual_status TEXT DEFAULT 'auto',
    days_of_week JSONB DEFAULT '["0", "1", "2", "3", "4", "5", "6"]'::jsonb,
    delivery_fee NUMERIC DEFAULT 2.00,
    combo_price NUMERIC DEFAULT 13.00,
    app_discount_percentage NUMERIC DEFAULT 0,
    is_app_discount_enabled BOOLEAN DEFAULT false,
    courier_access_code TEXT DEFAULT '012026',
    kitchen_printer TEXT,
    kitchen_printer_paper_width TEXT DEFAULT '80mm',
    bar_printer TEXT,
    bar_printer_paper_width TEXT DEFAULT '58mm',
    courier_printer TEXT,
    courier_printer_paper_width TEXT DEFAULT '58mm',
    printer_compatibility_mode TEXT DEFAULT 'false',
    preferred_printer TEXT,
    printer_paper_width TEXT DEFAULT '58mm',
    webhook_new_order_url TEXT,
    webhook_in_production_url TEXT,
    webhook_out_for_delivery_url TEXT,
    webhook_arrived_at_door_url TEXT,
    is_bot_enabled BOOLEAN DEFAULT false,
    is_rating_enabled BOOLEAN DEFAULT false,
    is_raffle_enabled BOOLEAN DEFAULT false,
    raffle_prize_value NUMERIC DEFAULT 50,
    raffle_draw_date TIMESTAMP WITH TIME ZONE,
    last_raffle_winner TEXT,
    bolao_start_time TIMESTAMP WITH TIME ZONE,
    bolao_end_time TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para settings" ON public.settings;
DROP POLICY IF EXISTS "Permite modificacao para settings" ON public.settings;
CREATE POLICY "Permite leitura publica para settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para settings" ON public.settings FOR ALL USING (true);

-- ------------------------------------------------------------
-- 6. CUSTOMERS (Base de Clientes)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    phone TEXT NOT NULL,
    name TEXT NOT NULL,
    address TEXT,
    reference_point TEXT,
    total_orders INT DEFAULT 0,
    last_order_at TIMESTAMP WITH TIME ZONE,
    ignore_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_store_customer_phone UNIQUE (store_id, phone)
);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para customers" ON public.customers;
DROP POLICY IF EXISTS "Permite modificacao para customers" ON public.customers;
CREATE POLICY "Permite leitura publica para customers" ON public.customers FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para customers" ON public.customers FOR ALL USING (true);

-- ------------------------------------------------------------
-- 7. COURIERS (Entregadores / Motoboys)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.couriers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    password TEXT NOT NULL DEFAULT '1234',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.couriers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para couriers" ON public.couriers;
DROP POLICY IF EXISTS "Permite modificacao para couriers" ON public.couriers;
CREATE POLICY "Permite leitura publica para couriers" ON public.couriers FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para couriers" ON public.couriers FOR ALL USING (true);

-- ------------------------------------------------------------
-- 8. ORDERS (Pedidos do Sistema)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    daily_order_number INT DEFAULT 0,
    comanda_number TEXT,
    table_number TEXT,
    order_type TEXT DEFAULT 'Entrega',
    customer_name TEXT,
    phone TEXT,
    address TEXT,
    reference_point TEXT,
    payment_method TEXT DEFAULT 'Dinheiro',
    change_for NUMERIC DEFAULT 0,
    items JSONB DEFAULT '[]'::jsonb,
    total NUMERIC NOT NULL DEFAULT 0,
    delivery_fee NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    tax NUMERIC DEFAULT 0,
    combo_price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Novo',
    status_history JSONB DEFAULT '[]'::jsonb,
    printed BOOLEAN DEFAULT false,
    origin TEXT DEFAULT 'APP',
    observation TEXT,
    rating INT,
    feedback TEXT,
    courier_id UUID REFERENCES public.couriers(id) ON DELETE SET NULL,
    courier_name TEXT,
    is_loyalty_eligible BOOLEAN DEFAULT true,
    loyalty_redeemed_at TIMESTAMP WITH TIME ZONE,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para orders" ON public.orders;
DROP POLICY IF EXISTS "Permite modificacao para orders" ON public.orders;
CREATE POLICY "Permite leitura publica para orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para orders" ON public.orders FOR ALL USING (true);

-- ------------------------------------------------------------
-- 9. CASH SESSIONS & TRANSACTIONS (Controle de Caixa)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cash_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'open',
    opening_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    closing_time TIMESTAMP WITH TIME ZONE,
    opening_float NUMERIC DEFAULT 0,
    closing_float NUMERIC DEFAULT 0,
    summary JSONB
);
ALTER TABLE public.cash_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para cash_sessions" ON public.cash_sessions;
DROP POLICY IF EXISTS "Permite modificacao para cash_sessions" ON public.cash_sessions;
CREATE POLICY "Permite leitura publica para cash_sessions" ON public.cash_sessions FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para cash_sessions" ON public.cash_sessions FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS public.cash_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    session_id UUID REFERENCES public.cash_sessions(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'Sangria' | 'Suprimento'
    amount NUMERIC NOT NULL,
    justification TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.cash_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para cash_transactions" ON public.cash_transactions;
DROP POLICY IF EXISTS "Permite modificacao para cash_transactions" ON public.cash_transactions;
CREATE POLICY "Permite leitura publica para cash_transactions" ON public.cash_transactions FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para cash_transactions" ON public.cash_transactions FOR ALL USING (true);

-- ------------------------------------------------------------
-- 10. PROMOTIONS (Promoções Ativas)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.promotions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT true
);
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permite leitura publica para promotions" ON public.promotions;
DROP POLICY IF EXISTS "Permite modificacao para promotions" ON public.promotions;
CREATE POLICY "Permite leitura publica para promotions" ON public.promotions FOR SELECT USING (true);
CREATE POLICY "Permite modificacao para promotions" ON public.promotions FOR ALL USING (true);

-- ============================================================
-- FUNÇÕES E TRIGGERS AUTOMÁTICOS
-- ============================================================

-- Trigger de Numeração Sequencial de Pedidos por Dia
CREATE OR REPLACE FUNCTION set_daily_order_number()
RETURNS TRIGGER AS $$
DECLARE
  next_num INTEGER;
BEGIN
  IF NEW.daily_order_number IS NULL OR NEW.daily_order_number = 0 THEN
      SELECT COALESCE(MAX(daily_order_number), 0) + 1
      INTO next_num
      FROM public.orders
      WHERE store_id = NEW.store_id
        AND date(timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo') = 
            date(NEW.timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo');
      
      NEW.daily_order_number := next_num;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_set_daily_order_number ON public.orders;
CREATE TRIGGER trigger_set_daily_order_number
BEFORE INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION set_daily_order_number();

-- Função N8N para Criação Externa de Pedidos (Bot WhatsApp)
CREATE OR REPLACE FUNCTION create_order_via_n8n(
    p_store_id UUID,
    p_customer JSONB,
    p_order JSONB,
    p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_customer_id UUID;
    v_order_id UUID;
    v_daily_number INTEGER;
    v_item JSONB;
    v_processed_items JSONB := '[]'::JSONB;
    v_total NUMERIC := 0;
    v_delivery_fee NUMERIC;
    v_customer_phone TEXT;
BEGIN
    IF jsonb_typeof(p_customer) = 'string' THEN p_customer := (p_customer #>> '{}')::jsonb; END IF;
    IF jsonb_typeof(p_order) = 'string' THEN p_order := (p_order #>> '{}')::jsonb; END IF;
    IF jsonb_typeof(p_items) = 'string' THEN p_items := (p_items #>> '{}')::jsonb; END IF;

    v_customer_phone := REGEXP_REPLACE(p_customer->>'phone', '\D', '', 'g');
    
    INSERT INTO public.customers (store_id, phone, name, address, reference_point, total_orders, last_order_at)
    VALUES (p_store_id, v_customer_phone, p_customer->>'name', p_customer->>'address', p_customer->>'reference', 1, NOW())
    ON CONFLICT (store_id, phone) DO UPDATE SET 
        name = EXCLUDED.name,
        address = COALESCE(NULLIF(EXCLUDED.address, ''), customers.address),
        reference_point = COALESCE(NULLIF(EXCLUDED.reference_point, ''), customers.reference_point),
        total_orders = customers.total_orders + 1,
        last_order_at = NOW()
    RETURNING id INTO v_customer_id;

    SELECT COALESCE(MAX(daily_order_number), 0) + 1
    INTO v_daily_number
    FROM public.orders
    WHERE store_id = p_store_id
      AND date(timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo') = 
          date(NOW() AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo');

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_total := v_total + (COALESCE((v_item->>'price')::NUMERIC, 0) * COALESCE((v_item->>'quantity')::INTEGER, 1));
        IF v_item->>'cartId' IS NULL THEN v_item := jsonb_set(v_item, '{cartId}', to_jsonb(gen_random_uuid())); END IF;
        IF v_item->>'selectedAddons' IS NULL THEN v_item := jsonb_set(v_item, '{selectedAddons}', '[]'::JSONB); END IF;
        v_processed_items := v_processed_items || v_item;
    END LOOP;

    v_delivery_fee := COALESCE((p_order->>'deliveryFee')::NUMERIC, 2.00);
    v_total := COALESCE((p_order->>'total')::NUMERIC, v_total + v_delivery_fee);

    INSERT INTO public.orders (
        store_id, daily_order_number, customer_name, phone, address, 
        reference_point, order_type, payment_method, status, 
        change_for, items, total, delivery_fee, timestamp, origin
    )
    VALUES (
        p_store_id, v_daily_number, p_customer->>'name', v_customer_phone, p_customer->>'address', 
        p_customer->>'reference', COALESCE(p_order->>'type', 'Entrega'), COALESCE(p_order->>'paymentMethod', 'Dinheiro'), 
        'Novo', (NULLIF(p_order->>'changeFor', ''))::NUMERIC, v_processed_items, v_total, v_delivery_fee, NOW(), 'AI'
    )
    RETURNING id INTO v_order_id;

    RETURN jsonb_build_object('success', true, 'orderId', v_order_id, 'dailyOrderNumber', v_daily_number);
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- ------------------------------------------------------------
-- INSERÇÃO DA LOJA PADRÃO E CONFIGURAÇÕES INICIAIS
-- ------------------------------------------------------------
DO $$ 
DECLARE
    new_store_id UUID;
BEGIN
    INSERT INTO public.stores (name, slug, logo_url, theme_colors, is_active)
    VALUES (
        'Açaí do Dudu',
        'acaidodudu',
        'https://firebasestorage.googleapis.com/v0/b/papaleguastoc.firebasestorage.app/o/menu-images%2Fstore_ea802c0f-4b61-4dc5-8325-cf3d23a0a392_1764413325339.png?alt=media&token=a40a2741-98a7-47fd-a213-d25d27a42693',
        '{"primary": "#800080", "secondary": "#4B0082", "background": "#121212", "surface": "#1E1E1E"}'::jsonb,
        true
    )
    ON CONFLICT (slug) DO NOTHING;

    SELECT id INTO new_store_id FROM public.stores WHERE slug = 'acaidodudu';

    IF new_store_id IS NOT NULL THEN
        INSERT INTO public.settings (store_id, opening_time, closing_time, manual_status, delivery_fee, courier_access_code)
        VALUES (new_store_id, '18:00:00', '23:30:00', 'auto', 2.00, '012026')
        ON CONFLICT (store_id) DO NOTHING;
    END IF;
END $$;

NOTIFY pgrst, 'reload schema';
